import { authenticatedFetch } from '@/auth/auth-api'
const URL = '/api/v1/inventory-audits'
export type AuditItem = { id: string; bookCopyId: string; barcode: string; expectedShelfId: string | null; actualShelfId: string | null; result: 'Pending' | 'Found' | 'Missing' | 'Misplaced' | 'Damaged'; scannedAtUtc: string | null }
export type InventoryAudit = { id: string; branchId: string; status: 'Draft' | 'InProgress' | 'Completed' | 'Cancelled'; startedAtUtc: string; completedAtUtc: string | null; concurrencyToken: string; totalItems: number; pendingItems: number; foundItems: number; missingItems: number; misplacedItems: number; items: AuditItem[] }
type Problem = { detail?: string; title?: string }
async function read<T>(response: Response): Promise<T> { if (response.ok) return response.json(); const problem = (await response.json().catch(() => null)) as Problem | null; throw new Error(problem?.detail ?? problem?.title ?? 'Không thể xử lý kiểm kê.') }
export async function createAudit(branchId: string, areaId?: string, shelfId?: string) { return read<InventoryAudit>(await authenticatedFetch(URL, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ branchId, areaId: areaId || null, shelfId: shelfId || null }) })) }
export async function getAudit(id: string) { return read<InventoryAudit>(await authenticatedFetch(`${URL}/${id}`)) }
export async function scanAudit(audit: InventoryAudit, barcode: string, result: AuditItem['result'] = 'Found', actualShelfId?: string) { return read<InventoryAudit>(await authenticatedFetch(`${URL}/${audit.id}/scan`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ barcode, result, actualShelfId: actualShelfId || null, concurrencyToken: audit.concurrencyToken }) })) }
export async function completeAudit(audit: InventoryAudit) { return read<InventoryAudit>(await authenticatedFetch(`${URL}/${audit.id}/complete`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ concurrencyToken: audit.concurrencyToken }) })) }
