using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using UTH.Library.Domain.Entities;
using UTH.Library.Infrastructure.Identity;

namespace UTH.Library.Infrastructure.Persistence.Configurations;

internal sealed class CatalogInventoryConfiguration :
    IEntityTypeConfiguration<Author>, IEntityTypeConfiguration<Publisher>, IEntityTypeConfiguration<Category>,
    IEntityTypeConfiguration<BookAuthor>, IEntityTypeConfiguration<BookCategory>, IEntityTypeConfiguration<Area>,
    IEntityTypeConfiguration<Shelf>, IEntityTypeConfiguration<BookCopy>, IEntityTypeConfiguration<InventoryAudit>,
    IEntityTypeConfiguration<InventoryAuditItem>, IEntityTypeConfiguration<Supplier>, IEntityTypeConfiguration<StockReceipt>,
    IEntityTypeConfiguration<StockReceiptItem>, IEntityTypeConfiguration<DiscrepancyReport>
{
    private static void Root<TEntity>(EntityTypeBuilder<TEntity> b, string table) where TEntity : class
    { b.ToTable(table); b.HasKey("Id"); b.Property<Guid>("ConcurrencyToken").IsConcurrencyToken().HasDefaultValueSql("gen_random_uuid()"); }
    public void Configure(EntityTypeBuilder<Author> b) { Root(b,"authors"); b.Property(x=>x.FullName).HasMaxLength(200).IsRequired(); b.Property(x=>x.Biography).HasMaxLength(2000); b.Property(x=>x.Status).HasConversion<string>().HasMaxLength(20); b.HasIndex(x=>x.FullName); }
    public void Configure(EntityTypeBuilder<Publisher> b) { Root(b,"publishers"); b.Property(x=>x.Name).HasMaxLength(200).IsRequired(); b.Property(x=>x.Address).HasMaxLength(500); b.Property(x=>x.ContactInfo).HasMaxLength(500); b.Property(x=>x.Status).HasConversion<string>().HasMaxLength(20); b.HasIndex(x=>x.Name).IsUnique(); }
    public void Configure(EntityTypeBuilder<Category> b) { Root(b,"categories"); b.Property(x=>x.Name).HasMaxLength(150).IsRequired(); b.Property(x=>x.Description).HasMaxLength(1000); b.Property(x=>x.Status).HasConversion<string>().HasMaxLength(20); b.HasIndex(x=>x.Name).IsUnique(); }
    public void Configure(EntityTypeBuilder<BookAuthor> b) { b.ToTable("book_authors"); b.HasKey(x=>new{x.BookId,x.AuthorId}); b.HasOne<Book>().WithMany().HasForeignKey(x=>x.BookId).OnDelete(DeleteBehavior.Cascade); b.HasOne<Author>().WithMany().HasForeignKey(x=>x.AuthorId).OnDelete(DeleteBehavior.Restrict); }
    public void Configure(EntityTypeBuilder<BookCategory> b) { b.ToTable("book_categories"); b.HasKey(x=>new{x.BookId,x.CategoryId}); b.HasOne<Book>().WithMany().HasForeignKey(x=>x.BookId).OnDelete(DeleteBehavior.Cascade); b.HasOne<Category>().WithMany().HasForeignKey(x=>x.CategoryId).OnDelete(DeleteBehavior.Restrict); }
    public void Configure(EntityTypeBuilder<Area> b) { Root(b,"areas"); b.Property(x=>x.Code).HasMaxLength(30).IsRequired(); b.Property(x=>x.Name).HasMaxLength(150).IsRequired(); b.HasIndex(x=>new{x.BranchId,x.Code}).IsUnique(); b.HasOne<Branch>().WithMany().HasForeignKey(x=>x.BranchId).OnDelete(DeleteBehavior.Restrict); }
    public void Configure(EntityTypeBuilder<Shelf> b) { Root(b,"shelves"); b.Property(x=>x.Code).HasMaxLength(30).IsRequired(); b.Property(x=>x.Label).HasMaxLength(150).IsRequired(); b.Property(x=>x.Status).HasConversion<string>().HasMaxLength(20); b.HasIndex(x=>new{x.AreaId,x.Code}).IsUnique(); b.HasOne<Area>().WithMany().HasForeignKey(x=>x.AreaId).OnDelete(DeleteBehavior.Restrict); }
    public void Configure(EntityTypeBuilder<BookCopy> b) { Root(b,"book_copies"); b.Property(x=>x.Barcode).HasMaxLength(64).IsRequired(); b.Property(x=>x.Condition).HasConversion<string>().HasMaxLength(20); b.Property(x=>x.Status).HasConversion<string>().HasMaxLength(20); b.Property(x=>x.AcquiredAtUtc).HasColumnType("timestamp with time zone"); b.HasIndex(x=>x.Barcode).IsUnique(); b.HasIndex(x=>new{x.BookId,x.Status}); b.HasOne<Book>().WithMany().HasForeignKey(x=>x.BookId).OnDelete(DeleteBehavior.Restrict); b.HasOne<Shelf>().WithMany().HasForeignKey(x=>x.ShelfId).OnDelete(DeleteBehavior.SetNull); b.HasOne<StockReceiptItem>().WithMany().HasForeignKey(x=>x.StockReceiptItemId).OnDelete(DeleteBehavior.SetNull); }
    public void Configure(EntityTypeBuilder<InventoryAudit> b) { Root(b,"inventory_audits"); b.Property(x=>x.Status).HasConversion<string>().HasMaxLength(20); b.Property(x=>x.StartedAtUtc).HasColumnType("timestamp with time zone"); b.Property(x=>x.CompletedAtUtc).HasColumnType("timestamp with time zone"); b.Property(x=>x.Notes).HasMaxLength(2000); b.HasIndex(x=>new{x.BranchId,x.Status}); b.HasOne<Branch>().WithMany().HasForeignKey(x=>x.BranchId).OnDelete(DeleteBehavior.Restrict); b.HasOne<ApplicationUser>().WithMany().HasForeignKey(x=>x.StartedByUserId).OnDelete(DeleteBehavior.Restrict); }
    public void Configure(EntityTypeBuilder<InventoryAuditItem> b) { Root(b,"inventory_audit_items"); b.Property(x=>x.Result).HasConversion<string>().HasMaxLength(20); b.Property(x=>x.ScannedAtUtc).HasColumnType("timestamp with time zone"); b.HasIndex(x=>new{x.InventoryAuditId,x.BookCopyId}).IsUnique(); b.HasOne<InventoryAudit>().WithMany().HasForeignKey(x=>x.InventoryAuditId).OnDelete(DeleteBehavior.Cascade); b.HasOne<BookCopy>().WithMany().HasForeignKey(x=>x.BookCopyId).OnDelete(DeleteBehavior.Restrict); b.HasOne<Shelf>().WithMany().HasForeignKey(x=>x.ExpectedShelfId).OnDelete(DeleteBehavior.SetNull); b.HasOne<Shelf>().WithMany().HasForeignKey(x=>x.ActualShelfId).OnDelete(DeleteBehavior.SetNull); }
    public void Configure(EntityTypeBuilder<Supplier> b) { Root(b,"suppliers"); b.Property(x=>x.Code).HasMaxLength(30).IsRequired(); b.Property(x=>x.Name).HasMaxLength(200).IsRequired(); b.Property(x=>x.Email).HasMaxLength(256); b.Property(x=>x.PhoneNumber).HasMaxLength(32); b.Property(x=>x.Address).HasMaxLength(500); b.HasIndex(x=>x.Code).IsUnique(); }
    public void Configure(EntityTypeBuilder<StockReceipt> b) { Root(b,"stock_receipts"); b.Property(x=>x.ReceiptNumber).HasMaxLength(50).IsRequired(); b.Property(x=>x.Status).HasConversion<string>().HasMaxLength(20); b.Property(x=>x.ReceivedAtUtc).HasColumnType("timestamp with time zone"); b.Property(x=>x.ConfirmedAtUtc).HasColumnType("timestamp with time zone"); b.Property(x=>x.Notes).HasMaxLength(2000); b.HasIndex(x=>x.ReceiptNumber).IsUnique(); b.HasOne<Supplier>().WithMany().HasForeignKey(x=>x.SupplierId).OnDelete(DeleteBehavior.Restrict); b.HasOne<Branch>().WithMany().HasForeignKey(x=>x.BranchId).OnDelete(DeleteBehavior.Restrict); b.HasOne<ApplicationUser>().WithMany().HasForeignKey(x=>x.ReceivedByUserId).OnDelete(DeleteBehavior.Restrict); }
    public void Configure(EntityTypeBuilder<StockReceiptItem> b) { Root(b,"stock_receipt_items"); b.Property(x=>x.UnitCost).HasPrecision(18,2); b.HasIndex(x=>new{x.StockReceiptId,x.BookId}).IsUnique(); b.HasOne<StockReceipt>().WithMany().HasForeignKey(x=>x.StockReceiptId).OnDelete(DeleteBehavior.Cascade); b.HasOne<Book>().WithMany().HasForeignKey(x=>x.BookId).OnDelete(DeleteBehavior.Restrict); }
    public void Configure(EntityTypeBuilder<DiscrepancyReport> b) { b.ToTable("discrepancy_reports"); b.HasKey(x=>x.Id); b.Property(x=>x.Type).HasConversion<string>().HasMaxLength(20); b.Property(x=>x.Description).HasMaxLength(2000).IsRequired(); b.Property(x=>x.CreatedAtUtc).HasColumnType("timestamp with time zone"); b.HasOne<StockReceipt>().WithMany().HasForeignKey(x=>x.StockReceiptId).OnDelete(DeleteBehavior.Cascade); }
}

internal sealed class OperationsConfiguration :
    IEntityTypeConfiguration<Renewal>, IEntityTypeConfiguration<CirculationPolicy>, IEntityTypeConfiguration<BorrowingLimitPolicy>,
    IEntityTypeConfiguration<FinePolicy>, IEntityTypeConfiguration<Report>, IEntityTypeConfiguration<SavedFilter>,
    IEntityTypeConfiguration<NotificationTemplate>, IEntityTypeConfiguration<Notification>, IEntityTypeConfiguration<SystemSetting>, IEntityTypeConfiguration<ConfigurationPackage>
{
    private static void Token<TEntity>(EntityTypeBuilder<TEntity> b) where TEntity:class => b.Property<Guid>("ConcurrencyToken").IsConcurrencyToken().HasDefaultValueSql("gen_random_uuid()");
    public void Configure(EntityTypeBuilder<Renewal> b) { b.ToTable("renewals"); b.HasKey(x=>x.Id); b.Property(x=>x.PreviousDueAtUtc).HasColumnType("timestamp with time zone"); b.Property(x=>x.NewDueAtUtc).HasColumnType("timestamp with time zone"); b.Property(x=>x.RenewedAtUtc).HasColumnType("timestamp with time zone"); b.HasIndex(x=>new{x.BorrowingId,x.RenewedAtUtc}); b.HasOne<Borrowing>().WithMany().HasForeignKey(x=>x.BorrowingId).OnDelete(DeleteBehavior.Cascade); b.HasOne<ApplicationUser>().WithMany().HasForeignKey(x=>x.RenewedByUserId).OnDelete(DeleteBehavior.Restrict); }
    public void Configure(EntityTypeBuilder<CirculationPolicy> b) { b.ToTable("circulation_policies"); b.HasKey(x=>x.Id); Token(b); b.Property(x=>x.Name).HasMaxLength(150).IsRequired(); b.Property(x=>x.EffectiveFrom).HasColumnType("timestamp with time zone"); b.Property(x=>x.EffectiveTo).HasColumnType("timestamp with time zone"); b.HasIndex(x=>x.IsActive); }
    public void Configure(EntityTypeBuilder<BorrowingLimitPolicy> b) { b.ToTable("borrowing_limit_policies"); b.HasKey(x=>x.Id); b.Property(x=>x.MemberType).HasMaxLength(50).IsRequired(); b.HasIndex(x=>new{x.CirculationPolicyId,x.MemberType}).IsUnique(); b.HasOne<CirculationPolicy>().WithMany().HasForeignKey(x=>x.CirculationPolicyId).OnDelete(DeleteBehavior.Cascade); }
    public void Configure(EntityTypeBuilder<FinePolicy> b) { b.ToTable("fine_policies"); b.HasKey(x=>x.Id); b.Property(x=>x.ViolationType).HasMaxLength(50).IsRequired(); b.Property(x=>x.AmountPerDay).HasPrecision(18,2); b.Property(x=>x.FixedAmount).HasPrecision(18,2); b.Property(x=>x.MaximumAmount).HasPrecision(18,2); b.HasIndex(x=>new{x.CirculationPolicyId,x.ViolationType}).IsUnique(); b.HasOne<CirculationPolicy>().WithMany().HasForeignKey(x=>x.CirculationPolicyId).OnDelete(DeleteBehavior.Cascade); }
    public void Configure(EntityTypeBuilder<Report> b) { b.ToTable("reports"); b.HasKey(x=>x.Id); Token(b); b.Property(x=>x.Code).HasMaxLength(50).IsRequired(); b.Property(x=>x.Name).HasMaxLength(200).IsRequired(); b.Property(x=>x.Type).HasConversion<string>().HasMaxLength(30); b.Property(x=>x.Definition).HasColumnType("jsonb"); b.Property(x=>x.CreatedAtUtc).HasColumnType("timestamp with time zone"); b.HasIndex(x=>x.Code).IsUnique(); b.HasOne<ApplicationUser>().WithMany().HasForeignKey(x=>x.CreatedByUserId).OnDelete(DeleteBehavior.Restrict); }
    public void Configure(EntityTypeBuilder<SavedFilter> b) { b.ToTable("saved_filters"); b.HasKey(x=>x.Id); b.Property(x=>x.Name).HasMaxLength(150).IsRequired(); b.Property(x=>x.Scope).HasMaxLength(100).IsRequired(); b.Property(x=>x.Criteria).HasColumnType("jsonb"); b.Property(x=>x.Sort).HasColumnType("jsonb"); b.Property(x=>x.CreatedAtUtc).HasColumnType("timestamp with time zone"); b.HasIndex(x=>new{x.OwnerUserId,x.Scope,x.Name}).IsUnique(); b.HasOne<ApplicationUser>().WithMany().HasForeignKey(x=>x.OwnerUserId).OnDelete(DeleteBehavior.Cascade); }
    public void Configure(EntityTypeBuilder<NotificationTemplate> b) { b.ToTable("notification_templates"); b.HasKey(x=>x.Id); Token(b); b.Property(x=>x.Code).HasMaxLength(50).IsRequired(); b.Property(x=>x.Name).HasMaxLength(150).IsRequired(); b.Property(x=>x.Channel).HasConversion<string>().HasMaxLength(20); b.Property(x=>x.SubjectTemplate).HasMaxLength(500); b.Property(x=>x.BodyTemplate).IsRequired(); b.Property(x=>x.UpdatedAtUtc).HasColumnType("timestamp with time zone"); b.HasIndex(x=>new{x.Code,x.Channel}).IsUnique(); }
    public void Configure(EntityTypeBuilder<Notification> b) { b.ToTable("notifications"); b.HasKey(x=>x.Id); Token(b); b.Property(x=>x.RecipientType).HasConversion<string>().HasMaxLength(20); b.Property(x=>x.Destination).HasMaxLength(256).IsRequired(); b.Property(x=>x.Subject).HasMaxLength(500); b.Property(x=>x.Body).IsRequired(); b.Property(x=>x.Status).HasConversion<string>().HasMaxLength(20); b.Property(x=>x.ScheduledAtUtc).HasColumnType("timestamp with time zone"); b.Property(x=>x.SentAtUtc).HasColumnType("timestamp with time zone"); b.Property(x=>x.FailureReason).HasMaxLength(2000); b.HasIndex(x=>new{x.Status,x.ScheduledAtUtc}); b.HasOne<NotificationTemplate>().WithMany().HasForeignKey(x=>x.TemplateId).OnDelete(DeleteBehavior.Restrict); }
    public void Configure(EntityTypeBuilder<SystemSetting> b) { b.ToTable("system_settings"); b.HasKey(x=>x.Id); Token(b); b.Property(x=>x.Key).HasMaxLength(150).IsRequired(); b.Property(x=>x.Value).HasColumnType("jsonb"); b.Property(x=>x.ValueType).HasConversion<string>().HasMaxLength(20); b.Property(x=>x.Description).HasMaxLength(1000); b.Property(x=>x.UpdatedAtUtc).HasColumnType("timestamp with time zone"); b.HasIndex(x=>x.Key).IsUnique(); b.HasOne<ApplicationUser>().WithMany().HasForeignKey(x=>x.UpdatedByUserId).OnDelete(DeleteBehavior.Restrict); }
    public void Configure(EntityTypeBuilder<ConfigurationPackage> b) { b.ToTable("configuration_packages"); b.HasKey(x=>x.Id); b.Property(x=>x.Version).HasMaxLength(50).IsRequired(); b.Property(x=>x.Data).HasColumnType("jsonb"); b.Property(x=>x.Checksum).HasMaxLength(128).IsRequired(); b.Property(x=>x.CreatedAtUtc).HasColumnType("timestamp with time zone"); b.HasIndex(x=>x.Checksum).IsUnique(); b.HasOne<ApplicationUser>().WithMany().HasForeignKey(x=>x.CreatedByUserId).OnDelete(DeleteBehavior.Restrict); }
}
