using System.ComponentModel.DataAnnotations;
using UTH.Library.Domain.Entities;
using UTH.Library.Application.Features.Members;
namespace UTH.Library.Api.Contracts.Members;
public sealed class MemberFilterRequest { public string? Search{get;init;} public MemberStatus? Status{get;init;} public string? MemberGroup{get;init;} [Range(1,1000000)] public int PageNumber{get;init;}=1; [Range(1,100)] public int PageSize{get;init;}=20; }
public sealed record SaveMemberRequest([Required,StringLength(30)]string MemberCode,[Required,StringLength(150)]string FullName,[Required,EmailAddress,StringLength(256)]string Email,[StringLength(30)]string? PhoneNumber,DateOnly? DateOfBirth,[StringLength(500)]string? Address,[Required,StringLength(100)]string MemberGroup,MemberStatus Status,[Range(1,100)]int BorrowingLimit,[Range(1,365)]int LoanPeriodDays,Guid? ConcurrencyToken=null);
public sealed record IssueCardRequest([Required,StringLength(50)]string CardNumber,DateOnly IssuedOn,DateOnly ExpiresOn,[Required]Guid ConcurrencyToken=default); public sealed record RenewCardRequest(DateOnly ExpiresOn,[Required]Guid ConcurrencyToken=default); public sealed record CardStatusRequest(MembershipCardStatus Status,[Required]Guid ConcurrencyToken=default);
public sealed record RestrictionRequest(MemberRestrictionType Type,[Required,StringLength(500)]string Reason,DateTime StartsAtUtc,DateTime? EndsAtUtc,[Required]Guid ConcurrencyToken); public sealed record RemoveRestrictionRequest([Required,StringLength(500)]string Reason,[Required]Guid ConcurrencyToken);
public sealed record PaymentRequest([Range(0.01,100000000)]decimal Amount,FinePaymentMethod Method,[StringLength(200)]string? Reference); public sealed record AdjustmentRequest([Range(-100000000,100000000)]decimal AmountDelta,[Required,StringLength(500)]string Reason);
public sealed record CardResponse(Guid Id,string CardNumber,DateOnly IssuedOn,DateOnly ExpiresOn,MembershipCardStatus Status); public sealed record RestrictionResponse(Guid Id,MemberRestrictionType Type,string Reason,DateTime StartsAtUtc,DateTime? EndsAtUtc,DateTime? RemovedAtUtc,string? RemovalReason,bool IsActive);
public sealed record BorrowingHistoryResponse(Guid Id,Guid BookId,DateTime BorrowedAtUtc,DateTime DueAtUtc,DateTime? ReturnedAtUtc); public sealed record ReservationHistoryResponse(Guid Id,Guid BookId,DateTime ReservedAtUtc,DateTime ExpiresAtUtc,DateTime? FulfilledAtUtc,DateTime? CancelledAtUtc);
public sealed record FineResponse(Guid Id,string Type,string BookTitle,string Note,decimal OriginalAmount,decimal AdjustmentTotal,decimal PaymentTotal,decimal Balance,DateTime RecordedAtUtc,string Status);
public sealed record MemberResponse(Guid Id,string MemberCode,string FullName,string Email,string? PhoneNumber,DateOnly? DateOfBirth,string? Address,string MemberGroup,MemberStatus Status,int BorrowingLimit,int LoanPeriodDays,Guid ConcurrencyToken,DateTime CreatedAtUtc,DateTime UpdatedAtUtc,CardResponse? Card,IReadOnlyList<RestrictionResponse> Restrictions,IReadOnlyList<BorrowingHistoryResponse> Borrowings,IReadOnlyList<ReservationHistoryResponse> Reservations,IReadOnlyList<FineResponse> Fines);
public sealed record MemberPageResponse(IReadOnlyList<MemberResponse> Items,int PageNumber,int PageSize,int TotalCount,int TotalPages);
public sealed class MemberHistoryFilterRequest { public MemberHistoryCategory Category{get;init;}=MemberHistoryCategory.Borrowings; [Range(1,1000000)]public int PageNumber{get;init;}=1; [Range(1,100)]public int PageSize{get;init;}=10; }
public sealed record MemberHistoryItemResponse(Guid Id,string Type,DateTime OccurredAtUtc,string Title,string Description,decimal? Amount);
public sealed record MemberHistoryPageResponse(IReadOnlyList<MemberHistoryItemResponse> Items,int PageNumber,int PageSize,int TotalCount,int TotalPages);
