using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using System.Security.Claims; using System.Text.Json; using UTH.Library.Api.Contracts.Members; using UTH.Library.Application.Abstractions.Identity; using UTH.Library.Application.Features.Members;
namespace UTH.Library.Api.Controllers;
[ApiController,Authorize,Route("api/v1/members")] public sealed class MembersController(MemberService service):ControllerBase {
 [HttpGet,Authorize(Policy=Permissions.MembersRead)] public async Task<ActionResult<MemberPageResponse>> Get([FromQuery]MemberFilterRequest r,CancellationToken ct){var p=await service.GetAsync(new(r.Search,r.Status,r.MemberGroup,r.PageNumber,r.PageSize),ct);return Ok(new MemberPageResponse(p.Items.Select(x=>Map(x,CanReadPii())).ToArray(),p.PageNumber,p.PageSize,p.TotalCount,p.TotalCount==0?0:(int)Math.Ceiling(p.TotalCount/(double)p.PageSize)));}
 [HttpGet("{id:guid}"),Authorize(Policy=Permissions.MembersRead)] public async Task<ActionResult<MemberResponse>> GetById(Guid id,CancellationToken ct){var x=await service.GetByIdAsync(id,ct);return x is null?NotFound():Ok(Map(x,CanReadPii()));}
 [HttpGet("{id:guid}/history"),Authorize(Policy=Permissions.MembersRead)] public async Task<ActionResult<MemberHistoryPageResponse>> History(Guid id,[FromQuery]MemberHistoryFilterRequest r,CancellationToken ct){var p=await service.GetHistoryAsync(id,r.Category,r.PageNumber,r.PageSize,ct);return p is null?NotFound():Ok(new MemberHistoryPageResponse(p.Items.Select(x=>new MemberHistoryItemResponse(x.Id,x.Type,x.OccurredAtUtc,x.Title,x.Description,x.Amount)).ToArray(),p.PageNumber,p.PageSize,p.TotalCount,p.TotalCount==0?0:(int)Math.Ceiling(p.TotalCount/(double)p.PageSize)));}
 [HttpPost,Authorize(Policy=Permissions.MembersCreate)] public async Task<ActionResult<MemberResponse>> Create(SaveMemberRequest r,CancellationToken ct){var result=await service.CreateAsync(Command(r),Actor(),ct);return result.Succeeded?CreatedAtAction(nameof(GetById),new{id=result.Member!.Id},Map(result.Member,CanReadPii())):Failure(result);}
 [HttpPut("{id:guid}"),Authorize(Policy=Permissions.MembersUpdate)] public async Task<ActionResult<MemberResponse>> Update(Guid id,SaveMemberRequest r,CancellationToken ct){var result=await service.UpdateAsync(id,Command(r),Actor(),ct);return result.Succeeded?Ok(Map(result.Member!,CanReadPii())):Failure(result);}
 [HttpPost("{id:guid}/card"),Authorize(Policy=Permissions.MembersManageCards)] public async Task<ActionResult<MemberResponse>> IssueCard(Guid id,[FromBody] JsonElement payload,CancellationToken ct) {
  var body = payload.ValueKind == JsonValueKind.Object && payload.TryGetProperty("request", out var wrapped)
   ? wrapped : payload;
  var cardNumber = body.ValueKind == JsonValueKind.Object && body.TryGetProperty("cardNumber", out var cardValue)
   ? cardValue.GetString() : null;
  var issuedOn = default(DateOnly);
  var expiresOn = default(DateOnly);
  var concurrencyToken = Guid.Empty;
  var issuedOnValid = body.ValueKind == JsonValueKind.Object && body.TryGetProperty("issuedOn", out var issuedValue) &&
   DateOnly.TryParse(issuedValue.GetString(), out issuedOn);
  var expiresOnValid = body.ValueKind == JsonValueKind.Object && body.TryGetProperty("expiresOn", out var expiresValue) &&
   DateOnly.TryParse(expiresValue.GetString(), out expiresOn);
  var tokenValid = body.ValueKind == JsonValueKind.Object && body.TryGetProperty("concurrencyToken", out var tokenValue) &&
   Guid.TryParse(tokenValue.GetString(), out concurrencyToken) && concurrencyToken != Guid.Empty;
  if (string.IsNullOrWhiteSpace(cardNumber) || !issuedOnValid || !expiresOnValid || !tokenValid)
   return BadRequest(new ValidationProblemDetails(new Dictionary<string,string[]> {
    ["card"] = ["Số thẻ, ngày cấp, ngày hết hạn và phiên bản độc giả là bắt buộc."] }));
  return Result(await service.IssueCardAsync(id,cardNumber,issuedOn,expiresOn,concurrencyToken,Actor(),ct));
 }
 [HttpPost("{id:guid}/card/renew"),Authorize(Policy=Permissions.MembersManageCards)] public async Task<ActionResult<MemberResponse>> RenewCard(Guid id,RenewCardRequest r,CancellationToken ct)=>Result(await service.RenewCardAsync(id,r.ExpiresOn,r.ConcurrencyToken,Actor(),ct));
 [HttpPatch("{id:guid}/card/status"),Authorize(Policy=Permissions.MembersManageCards)] public async Task<ActionResult<MemberResponse>> CardStatus(Guid id,CardStatusRequest r,CancellationToken ct)=>Result(await service.ChangeCardStatusAsync(id,r.Status,r.ConcurrencyToken,Actor(),ct));
 [HttpPost("{id:guid}/restrictions"),Authorize(Policy=Permissions.MembersManageRestrictions)] public async Task<ActionResult<MemberResponse>> Restrict(Guid id,RestrictionRequest r,CancellationToken ct)=>Result(await service.AddRestrictionAsync(id,r.Type,r.Reason,r.StartsAtUtc,r.EndsAtUtc,r.ConcurrencyToken,Actor(),ct));
 [HttpPost("{id:guid}/restrictions/{restrictionId:guid}/remove"),Authorize(Policy=Permissions.MembersManageRestrictions)] public async Task<ActionResult<MemberResponse>> RemoveRestriction(Guid id,Guid restrictionId,RemoveRestrictionRequest r,CancellationToken ct)=>Result(await service.RemoveRestrictionAsync(id,restrictionId,r.Reason,r.ConcurrencyToken,Actor(),ct));
 [HttpPost("{id:guid}/violations/{violationId:guid}/payments"),Authorize(Policy=Permissions.MembersManageFinances)] public async Task<ActionResult<MemberResponse>> Payment(Guid id,Guid violationId,PaymentRequest r,CancellationToken ct)=>Result(await service.AddPaymentAsync(id,violationId,r.Amount,r.Method,r.Reference,Actor(),ct));
 [HttpPost("{id:guid}/violations/{violationId:guid}/adjustments"),Authorize(Policy=Permissions.MembersManageFinances)] public async Task<ActionResult<MemberResponse>> Adjustment(Guid id,Guid violationId,AdjustmentRequest r,CancellationToken ct)=>Result(await service.AddAdjustmentAsync(id,violationId,r.AmountDelta,r.Reason,Actor(),ct));
 private ActionResult<MemberResponse> Result(MemberResult r)=>r.Succeeded?Ok(Map(r.Member!,CanReadPii())):Failure(r); private ActionResult<MemberResponse> Failure(MemberResult r){var p=new ProblemDetails{Detail=r.Errors.FirstOrDefault()};return r.Failure switch{MemberFailure.NotFound=>NotFound(p),MemberFailure.Conflict=>Conflict(p),_=>BadRequest(p)};}
 private Guid? Actor()=>Guid.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier)??User.FindFirstValue("sub"),out var id)?id:null; private static SaveMemberCommand Command(SaveMemberRequest r)=>new(r.MemberCode,r.FullName,r.Email,r.PhoneNumber,r.DateOfBirth,r.Address,r.MemberGroup,r.Status,r.BorrowingLimit,r.LoanPeriodDays,r.ConcurrencyToken);
 private bool CanReadPii()=>User.HasClaim("permission",Permissions.MembersUpdate);
 private static MemberResponse Map(MemberModel m,bool pii)=>new(m.Id,m.MemberCode,m.FullName,pii?m.Email:"***",pii?m.PhoneNumber:null,pii?m.DateOfBirth:null,pii?m.Address:null,m.MemberGroup,m.Status,m.BorrowingLimit,m.LoanPeriodDays,m.ConcurrencyToken,m.CreatedAtUtc,m.UpdatedAtUtc,m.Card is null?null:new(m.Card.Id,m.Card.CardNumber,m.Card.IssuedOn,m.Card.ExpiresOn,m.Card.Status),m.Restrictions.Select(x=>new RestrictionResponse(x.Id,x.Type,x.Reason,x.StartsAtUtc,x.EndsAtUtc,x.RemovedAtUtc,x.RemovalReason,x.IsActive)).ToArray(),m.Borrowings.Select(x=>new BorrowingHistoryResponse(x.Id,x.BookId,x.BorrowedAtUtc,x.DueAtUtc,x.ReturnedAtUtc)).ToArray(),m.Reservations.Select(x=>new ReservationHistoryResponse(x.Id,x.BookId,x.ReservedAtUtc,x.ExpiresAtUtc,x.FulfilledAtUtc,x.CancelledAtUtc)).ToArray(),m.Fines.Select(x=>new FineResponse(x.Id,x.Type,x.BookTitle,x.Note,x.OriginalAmount,x.AdjustmentTotal,x.PaymentTotal,x.Balance,x.RecordedAtUtc,x.Status)).ToArray());
}
