import { useEffect, useState } from 'react'
import { Pencil, Plus, RefreshCw, Search, XCircle } from 'lucide-react'
import { Button } from '@/common/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/common/components/ui/card'
import { Input } from '@/common/components/ui/input'
import { PageShell, ScreenState, StatusBadge, useToast } from '@/common/components'
import { PermissionBoundary } from '@/shared/auth/PermissionBoundary'
import { createSupplier, deactivateSupplier, getSuppliers, updateSupplier, type Supplier, type SupplierInput, type SupplierStatus } from './supplier-api'

const empty: SupplierInput = { code: '', name: '', contactName: '', email: '', phoneNumber: '', address: '' }
export function SuppliersPage() {
  const [items, setItems] = useState<Supplier[]>([]); const [search, setSearch] = useState(''); const [status, setStatus] = useState<SupplierStatus | ''>(''); const [form, setForm] = useState<SupplierInput>(empty); const [editing, setEditing] = useState<Supplier | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [formError, setFormError] = useState(''); const { showToast } = useToast()
  const load = () => { setLoading(true); setError(''); getSuppliers(search.trim() || undefined, status || undefined).then((page) => setItems(page.items)).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Không thể tải nhà cung cấp.')).finally(() => setLoading(false)) }
  useEffect(load, [status])
  const save = async () => { setFormError(''); try { const saved = editing ? await updateSupplier(editing.id, { ...form, concurrencyToken: editing.concurrencyToken }) : await createSupplier(form); setItems((current) => editing ? current.map((item) => item.id === saved.id ? saved : item) : [saved, ...current]); setEditing(null); setForm(empty); showToast('Đã lưu nhà cung cấp.') } catch (reason) { setFormError(reason instanceof Error ? reason.message : 'Không thể lưu nhà cung cấp.') } }
  const deactivate = async (supplier: Supplier) => { setFormError(''); try { await deactivateSupplier(supplier); setItems((current) => current.map((item) => item.id === supplier.id ? { ...item, status: 'Inactive' } : item)); showToast('Đã ngừng hoạt động nhà cung cấp.') } catch (reason) { setFormError(reason instanceof Error ? reason.message : 'Không thể ngừng hoạt động nhà cung cấp.') } }
  return <PageShell eyebrow="Nhập kho" title="Nhà cung cấp" description="Quản lý thông tin liên hệ và trạng thái nhà cung cấp." actions={<><Button variant="outline" onClick={load}><RefreshCw className={loading ? 'animate-spin' : ''} /> Làm mới</Button><PermissionBoundary requiredPermissions={['suppliers.create']}><Button onClick={() => { setEditing(null); setForm(empty) }}><Plus /> Thêm nhà cung cấp</Button></PermissionBoundary></>}>
    <Card><CardContent className="flex flex-col gap-3 p-5 sm:flex-row"><div className="relative flex-1"><Search className="pointer-events-none absolute top-1/2 left-3 size-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-9" value={search} onChange={(event) => setSearch(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && load()} placeholder="Mã, tên, liên hệ, email" aria-label="Tìm nhà cung cấp" /></div><select className="h-10 rounded-md border bg-background px-3 text-sm" value={status} onChange={(event) => setStatus(event.target.value as SupplierStatus | '')}><option value="">Mọi trạng thái</option><option value="Active">Đang hoạt động</option><option value="Inactive">Ngừng hoạt động</option></select><Button onClick={load}>Tìm kiếm</Button></CardContent></Card>
    <Card className="mt-4"><CardHeader><CardTitle>Danh sách nhà cung cấp</CardTitle></CardHeader><CardContent>{formError ? <div className="mb-4 rounded-md border border-destructive/30 bg-destructive/5 p-3 text-sm">{formError}</div> : null}{loading ? <p className="p-6 text-center">Đang tải...</p> : error ? <ScreenState kind="error" title="Không thể tải nhà cung cấp" description={error} actionLabel="Thử lại" onAction={load} /> : items.length === 0 ? <ScreenState kind="empty" title="Chưa có nhà cung cấp" /> : <div className="grid gap-3">{items.map((supplier) => <div key={supplier.id} className="flex flex-col justify-between gap-3 rounded-md border p-4 md:flex-row md:items-center"><div><p className="font-semibold">{supplier.code} · {supplier.name}</p><p className="text-sm text-muted-foreground">{supplier.contactName || 'Chưa có người liên hệ'} · {supplier.email || 'Chưa có email'} · {supplier.phoneNumber || 'Chưa có số điện thoại'}</p><p className="text-xs text-muted-foreground">{supplier.hasStockReceipts ? 'Có lịch sử phiếu nhập' : 'Chưa có phiếu nhập'}</p></div><div className="flex items-center gap-2"><StatusBadge label={supplier.status === 'Active' ? 'Đang hoạt động' : 'Ngừng hoạt động'} tone={supplier.status === 'Active' ? 'success' : 'danger'} /><PermissionBoundary requiredPermissions={['suppliers.update']}><Button variant="ghost" size="icon" aria-label={`Sửa ${supplier.name}`} onClick={() => { setEditing(supplier); setForm({ code: supplier.code, name: supplier.name, contactName: supplier.contactName, email: supplier.email, phoneNumber: supplier.phoneNumber, address: supplier.address }) }}><Pencil /></Button></PermissionBoundary><PermissionBoundary requiredPermissions={['suppliers.deactivate']}><Button variant="ghost" size="icon" disabled={supplier.status === 'Inactive'} aria-label={`Ngừng ${supplier.name}`} onClick={() => deactivate(supplier)}><XCircle /></Button></PermissionBoundary></div></div>)}</div>}</CardContent></Card>
    <Card className="mt-4"><CardHeader><CardTitle>{editing ? 'Cập nhật nhà cung cấp' : 'Tạo nhà cung cấp nhanh'}</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2"><Input placeholder="Mã nhà cung cấp" value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value })} /><Input placeholder="Tên nhà cung cấp" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><Input placeholder="Người liên hệ" value={form.contactName ?? ''} onChange={(e) => setForm({ ...form, contactName: e.target.value })} /><Input placeholder="Email" type="email" value={form.email ?? ''} onChange={(e) => setForm({ ...form, email: e.target.value })} /><Input placeholder="Số điện thoại" value={form.phoneNumber ?? ''} onChange={(e) => setForm({ ...form, phoneNumber: e.target.value })} /><Input placeholder="Địa chỉ" value={form.address ?? ''} onChange={(e) => setForm({ ...form, address: e.target.value })} /><Button className="md:col-span-2" onClick={save}>{editing ? 'Lưu thay đổi' : 'Tạo nhà cung cấp'}</Button></CardContent></Card>
  </PageShell>
}
