// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UTH.Library.Infrastructure.Persistence;

#nullable disable

namespace UTH.Library.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20260908160655_DecoupleAuditActor")]
    partial class DecoupleAuditActor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("CredentialId")
                        .HasColumnType("bytea");

                    b.HasKey("UserId", "CredentialId");

                    b.ToTable("UserPasskeys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("10000000-0000-0000-0000-000000000001"),
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("UTH.Library.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId", "CreatedAtUtc");

                    b.HasIndex("EntityType", "EntityId", "CreatedAtUtc");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("UTH.Library.Domain.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Isbn")
                        .IsUnique();

                    b.HasIndex("Title");

                    b.ToTable("books", (string)null);
                });

            modelBuilder.Entity("UTH.Library.Domain.Entities.Borrowing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BorrowedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BorrowerEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("BorrowerId")
                        .HasColumnType("uuid");

                    b.Property<string>("BorrowerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("DueAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReturnedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DueAtUtc");

                    b.HasIndex("BookId", "BorrowerId", "ReturnedAtUtc");

                    b.ToTable("borrowings", (string)null);
                });

            modelBuilder.Entity("UTH.Library.Domain.Entities.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.ToTable("branches", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            Code = "MAIN",
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Main Library",
                            UpdatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("UTH.Library.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("Department");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("UTH.Library.Domain.Entities.FineAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AdjustedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AdjustedByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountDelta")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ViolationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ViolationId");

                    b.HasIndex("MemberId", "ViolationId");

                    b.ToTable("fine_adjustments", (string)null);
                });

            modelBuilder.Entity("UTH.Library.Domain.Entities.FinePayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("PaidAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReceivedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ViolationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ViolationId");

                    b.HasIndex("MemberId", "ViolationId");

                    b.ToTable("fine_payments", (string)null);
                });

            modelBuilder.Entity("UTH.Library.Domain.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("BorrowingLimit")
                        .HasColumnType("integer");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("LoanPeriodDays")
                        .HasColumnType("integer");

                    b.Property<string>("MemberCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("MemberGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MemberCode")
                        .IsUnique();

                    b.HasIndex("MemberGroup");

                    b.HasIndex("Status");

                    b.ToTable("members", (string)null);
                });

            modelBuilder.Entity("UTH.Library.Domain.Entities.MemberRestriction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RemovalReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("RemovedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RemovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId", "RemovedAtUtc");

                    b.ToTable("member_restrictions", (string)null);
                });

            modelBuilder.Entity("UTH.Library.Domain.Entities.MembershipCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("ExpiresOn")
                        .HasColumnType("date");

                    b.Property<DateOnly>("IssuedOn")
                        .HasColumnType("date");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CardNumber")
                        .IsUnique();

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.ToTable("membership_cards", (string)null);
                });

            modelBuilder.Entity("UTH.Library.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FulfilledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReserverEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("ReserverId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReserverName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("BookId", "ReserverId", "FulfilledAtUtc", "CancelledAtUtc");

                    b.ToTable("reservations", (string)null);
                });

            modelBuilder.Entity("UTH.Library.Domain.Entities.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("todos", (string)null);
                });

            modelBuilder.Entity("UTH.Library.Domain.Entities.Violation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BookId")
                        .HasColumnType("uuid");

                    b.Property<string>("BookTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("BorrowerEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("BorrowerId")
                        .HasColumnType("uuid");

                    b.Property<string>("BorrowerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("FineAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Resolution")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAtUtc");

                    b.HasIndex("BorrowerId", "ResolvedAtUtc");

                    b.ToTable("violations", (string)null);
                });

            modelBuilder.Entity("UTH.Library.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            ConcurrencyStamp = "20000000-0000-0000-0000-000000000002",
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full system access.",
                            IsSystemRole = true,
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("UTH.Library.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "10000000-0000-0000-0000-000000000003",
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "System Administrator",
                            Email = "admin@example.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN@EXAMPLE.COM",
                            PasswordHash = "$argon2id$v=19$m=65536,t=3,p=2$gbASegqg+aS71bLWtCPomQ==$3AHGi//TyjMTP6Rj34P/L5yNoeZWZoEHMs2qZ+zMHd0=",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "10000000-0000-0000-0000-000000000002",
                            TwoFactorEnabled = false,
                            UserName = "admin@example.com"
                        });
                });

            modelBuilder.Entity("UTH.Library.Infrastructure.Identity.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Read users.",
                            Module = "users",
                            Name = "users.read"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create users.",
                            Module = "users",
                            Name = "users.create"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Update users.",
                            Module = "users",
                            Name = "users.update"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Deactivate users.",
                            Module = "users",
                            Name = "users.deactivate"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Read roles.",
                            Module = "roles",
                            Name = "roles.read"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000006"),
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create roles.",
                            Module = "roles",
                            Name = "roles.create"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000007"),
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Update roles.",
                            Module = "roles",
                            Name = "roles.update"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000008"),
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Assign roles and permissions.",
                            Module = "roles",
                            Name = "roles.assign"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000009"),
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Read permissions.",
                            Module = "permissions",
                            Name = "permissions.read"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000010"),
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Read todos.",
                            Module = "todos",
                            Name = "todos.read"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000011"),
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create todos.",
                            Module = "todos",
                            Name = "todos.create"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000012"),
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Update todos.",
                            Module = "todos",
                            Name = "todos.update"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000013"),
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Delete todos.",
                            Module = "todos",
                            Name = "todos.delete"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000018"),
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Read books.",
                            Module = "books",
                            Name = "books.read"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000019"),
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create books.",
                            Module = "books",
                            Name = "books.create"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000020"),
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Update books.",
                            Module = "books",
                            Name = "books.update"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000021"),
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Delete books.",
                            Module = "books",
                            Name = "books.delete"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000014"),
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Read employees.",
                            Module = "employees",
                            Name = "employees.read"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000015"),
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create employees.",
                            Module = "employees",
                            Name = "employees.create"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000016"),
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Update employees.",
                            Module = "employees",
                            Name = "employees.update"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000017"),
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Delete employees.",
                            Module = "employees",
                            Name = "employees.delete"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000022"),
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Read borrowings.",
                            Module = "borrowings",
                            Name = "borrowings.read"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000023"),
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create borrowings.",
                            Module = "borrowings",
                            Name = "borrowings.create"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000024"),
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Return borrowings.",
                            Module = "borrowings",
                            Name = "borrowings.return"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000025"),
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Read reservations.",
                            Module = "reservations",
                            Name = "reservations.read"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000026"),
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create reservations.",
                            Module = "reservations",
                            Name = "reservations.create"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000027"),
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cancel reservations.",
                            Module = "reservations",
                            Name = "reservations.cancel"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000028"),
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fulfill reservations.",
                            Module = "reservations",
                            Name = "reservations.fulfill"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000029"),
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Read violations.",
                            Module = "violations",
                            Name = "violations.read"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000030"),
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create violations.",
                            Module = "violations",
                            Name = "violations.create"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000031"),
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Resolve violations.",
                            Module = "violations",
                            Name = "violations.resolve"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000032"),
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Read member profiles and history.",
                            Module = "members",
                            Name = "members.read"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000033"),
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create member profiles.",
                            Module = "members",
                            Name = "members.create"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000034"),
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Update member profiles and limits.",
                            Module = "members",
                            Name = "members.update"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000035"),
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Issue and maintain membership cards.",
                            Module = "members",
                            Name = "members.manage-cards"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000036"),
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manage member transaction restrictions.",
                            Module = "members",
                            Name = "members.manage-restrictions"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000037"),
                            CreatedAtUtc = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Record fine payments and adjustments.",
                            Module = "members",
                            Name = "members.manage-finances"
                        });
                });

            modelBuilder.Entity("UTH.Library.Infrastructure.Identity.RefreshTokenSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentTokenId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAtUtc");

                    b.ToTable("refresh_token_sessions", (string)null);
                });

            modelBuilder.Entity("UTH.Library.Infrastructure.Identity.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000018")
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000019")
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000020")
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000021")
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000014")
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000015")
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000016")
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000017")
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000022")
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000023")
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000024")
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000025")
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000026")
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000027")
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000028")
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000029")
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000030")
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000031")
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000032")
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000033")
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000034")
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000035")
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000036")
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000037")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("UTH.Library.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("UTH.Library.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("UTH.Library.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<System.Guid>", b =>
                {
                    b.OwnsOne("Microsoft.AspNetCore.Identity.IdentityPasskeyData", "Data", b1 =>
                        {
                            b1.Property<Guid>("IdentityUserPasskeyUserId")
                                .HasColumnType("uuid");

                            b1.Property<byte[]>("IdentityUserPasskeyCredentialId")
                                .HasColumnType("bytea");

                            b1.Property<byte[]>("AttestationObject")
                                .IsRequired()
                                .HasColumnType("bytea");

                            b1.Property<byte[]>("ClientDataJson")
                                .IsRequired()
                                .HasColumnType("bytea");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsBackedUp")
                                .HasColumnType("boolean");

                            b1.Property<bool>("IsBackupEligible")
                                .HasColumnType("boolean");

                            b1.Property<bool>("IsUserVerified")
                                .HasColumnType("boolean");

                            b1.Property<string>("Name")
                                .HasColumnType("text");

                            b1.Property<byte[]>("PublicKey")
                                .IsRequired()
                                .HasColumnType("bytea");

                            b1.Property<long>("SignCount")
                                .HasColumnType("bigint");

                            b1.PrimitiveCollection<string[]>("Transports")
                                .HasColumnType("text[]");

                            b1.HasKey("IdentityUserPasskeyUserId", "IdentityUserPasskeyCredentialId");

                            b1.ToTable("UserPasskeys");

                            b1.WithOwner()
                                .HasForeignKey("IdentityUserPasskeyUserId", "IdentityUserPasskeyCredentialId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("UTH.Library.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UTH.Library.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("UTH.Library.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UTH.Library.Domain.Entities.Employee", b =>
                {
                    b.HasOne("UTH.Library.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UTH.Library.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("UTH.Library.Domain.Entities.Employee", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("UTH.Library.Domain.Entities.FineAdjustment", b =>
                {
                    b.HasOne("UTH.Library.Domain.Entities.Violation", null)
                        .WithMany()
                        .HasForeignKey("ViolationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UTH.Library.Domain.Entities.FinePayment", b =>
                {
                    b.HasOne("UTH.Library.Domain.Entities.Violation", null)
                        .WithMany()
                        .HasForeignKey("ViolationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UTH.Library.Domain.Entities.MemberRestriction", b =>
                {
                    b.HasOne("UTH.Library.Domain.Entities.Member", null)
                        .WithMany("Restrictions")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UTH.Library.Domain.Entities.MembershipCard", b =>
                {
                    b.HasOne("UTH.Library.Domain.Entities.Member", null)
                        .WithOne("MembershipCard")
                        .HasForeignKey("UTH.Library.Domain.Entities.MembershipCard", "MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UTH.Library.Infrastructure.Identity.RefreshTokenSession", b =>
                {
                    b.HasOne("UTH.Library.Infrastructure.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UTH.Library.Infrastructure.Identity.RolePermission", b =>
                {
                    b.HasOne("UTH.Library.Infrastructure.Identity.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UTH.Library.Infrastructure.Identity.ApplicationRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("UTH.Library.Domain.Entities.Member", b =>
                {
                    b.Navigation("MembershipCard");

                    b.Navigation("Restrictions");
                });
#pragma warning restore 612, 618
        }
    }
}
