import { useEffect, useState } from 'react'
import { Plus, RefreshCw, Save, Trash2 } from 'lucide-react'
import { Button } from '@/common/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/common/components/ui/card'
import { Input } from '@/common/components/ui/input'
import { PageShell, ScreenState, StatusBadge, useToast } from '@/common/components'
import { PermissionBoundary } from '@/shared/auth/PermissionBoundary'
import { createReceipt, getReceipts, type StockReceipt } from './receipt-api'

type DraftLine = { bookId: string; expectedQuantity: string; receivedQuantity: string; damagedQuantity: string; unitCost: string }
const emptyLine = (): DraftLine => ({ bookId: '', expectedQuantity: '1', receivedQuantity: '0', damagedQuantity: '0', unitCost: '0' })
export function StockReceiptsPage() {
  const [receipts, setReceipts] = useState<StockReceipt[]>([]); const [supplierId, setSupplierId] = useState(''); const [branchId, setBranchId] = useState(''); const [notes, setNotes] = useState(''); const [lines, setLines] = useState<DraftLine[]>([emptyLine()]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const { showToast } = useToast()
  const load = () => { setLoading(true); getReceipts().then((page) => setReceipts(page.items)).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Không thể tải phiếu nhập.')).finally(() => setLoading(false)) }
  useEffect(load, [])
  const totalQuantity = lines.reduce((total, line) => total + Number(line.receivedQuantity || 0), 0); const totalValue = lines.reduce((total, line) => total + Number(line.receivedQuantity || 0) * Number(line.unitCost || 0), 0)
  const save = async () => { setSaving(true); setError(''); try { await createReceipt({ supplierId, branchId, receivedAtUtc: new Date().toISOString(), notes, items: lines.map((line) => ({ bookId: line.bookId, expectedQuantity: Number(line.expectedQuantity), receivedQuantity: Number(line.receivedQuantity), damagedQuantity: Number(line.damagedQuantity), unitCost: Number(line.unitCost) })) }); setLines([emptyLine()]); setNotes(''); load(); showToast('Đã lưu phiếu nhập nháp.') } catch (reason) { setError(reason instanceof Error ? reason.message : 'Không thể lưu phiếu nhập.') } finally { setSaving(false) } }
  return <PageShell eyebrow="Nhập kho" title="Phiếu nhập sách" description="Tạo phiếu nhập nháp, nhập nhiều dòng sách và kiểm tra tổng số liệu." actions={<Button variant="outline" onClick={load}><RefreshCw className={loading ? 'animate-spin' : ''} /> Làm mới</Button>}>
    <Card><CardHeader><CardTitle>Phiếu nhập nháp</CardTitle></CardHeader><CardContent className="grid gap-4"><div className="grid gap-3 md:grid-cols-2"><Input placeholder="Supplier ID" value={supplierId} onChange={(e) => setSupplierId(e.target.value)} /><Input placeholder="Branch ID" value={branchId} onChange={(e) => setBranchId(e.target.value)} /></div><Input placeholder="Ghi chú" value={notes} onChange={(e) => setNotes(e.target.value)} />{lines.map((line, index) => <div className="grid gap-2 rounded-md border p-3 md:grid-cols-[1.5fr_repeat(4,1fr)_auto]" key={index}><Input placeholder="Book ID / ISBN lookup" value={line.bookId} onChange={(e) => setLines((all) => all.map((item, i) => i === index ? { ...item, bookId: e.target.value } : item))} /><Input type="number" min={0} placeholder="Dự kiến" value={line.expectedQuantity} onChange={(e) => setLines((all) => all.map((item, i) => i === index ? { ...item, expectedQuantity: e.target.value } : item))} /><Input type="number" min={0} placeholder="Thực nhận" value={line.receivedQuantity} onChange={(e) => setLines((all) => all.map((item, i) => i === index ? { ...item, receivedQuantity: e.target.value } : item))} /><Input type="number" min={0} placeholder="Hỏng" value={line.damagedQuantity} onChange={(e) => setLines((all) => all.map((item, i) => i === index ? { ...item, damagedQuantity: e.target.value } : item))} /><Input type="number" min={0} placeholder="Đơn giá" value={line.unitCost} onChange={(e) => setLines((all) => all.map((item, i) => i === index ? { ...item, unitCost: e.target.value } : item))} /><Button variant="ghost" size="icon" aria-label="Xóa dòng" disabled={lines.length === 1} onClick={() => setLines((all) => all.filter((_, i) => i !== index))}><Trash2 /></Button></div>)}<Button variant="outline" onClick={() => setLines((all) => [...all, emptyLine()])}><Plus /> Thêm dòng</Button><div className="flex flex-wrap justify-between gap-3 border-t pt-4 text-sm"><span>Tổng thực nhận: <strong>{totalQuantity}</strong></span><span>Tổng giá trị: <strong>{totalValue.toLocaleString('vi-VN')}</strong></span><PermissionBoundary requiredPermissions={['stock-receipts.create']}><Button disabled={saving} onClick={save}><Save /> Lưu nháp</Button></PermissionBoundary></div>{error ? <div className="rounded-md border border-destructive/30 bg-destructive/5 p-3 text-sm">{error}</div> : null}</CardContent></Card>
    <Card className="mt-4"><CardHeader><CardTitle>Lịch sử phiếu nhập</CardTitle></CardHeader><CardContent>{loading ? <p className="p-6 text-center">Đang tải...</p> : receipts.length === 0 ? <ScreenState kind="empty" title="Chưa có phiếu nhập" /> : <div className="grid gap-3">{receipts.map((receipt) => <div className="flex items-center justify-between rounded-md border p-4" key={receipt.id}><div><p className="font-semibold">{receipt.receiptNumber}</p><p className="text-sm text-muted-foreground">{receipt.totalQuantity} quyển · {receipt.totalValue.toLocaleString('vi-VN')}</p></div><StatusBadge label={receipt.status} tone={receipt.status === 'Draft' ? 'neutral' : 'success'} /></div>)}</div>}</CardContent></Card>
  </PageShell>
}
